### ISSUE TITLE
RuntimeError: Expected kernel_size[0] * kernel_size[1] < 16 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### ISSUE THREAD

**Issue by CuberrChen** [ucbrise/actnn#10]
when i did't apply the actnn, there is no the issue. so I dont donw if there is a limitation of the kernel size if i want to use actnn?

**Comment by merrymercy** [comment]
This error is caused by our own implementation of MaxPool2d. It seems you are using max pooling with a large kernel size.
Currently, our kernel implementation does not support this case. You can disable our quantized max-pooling layers by deleting these lines
https://github.com/ucbrise/actnn/blob/aa4f43cce6631f53c3ed965b34b6de66bfe04c0a/actnn/actnn/module.py#L67-L72
But the memory usage will be higher.

We use our own implementation of MaxPool2d because we found the default one in PyTorch is not memory efficient. If you know how to write CUDA kernel, you can try to extend our code to support larger kernel sizes.

**Comment by CuberrChen** [comment]
Thank you very much for your detailed answer!
