### ISSUE TITLE
how to deploy actnn by libtorch?

### ISSUE THREAD

**Issue by lucify123** [ucbrise/actnn#11]
It's really an interesting work！I just wonder how can we deploy actnn using libtorch. With libtorch or onnx( from python to c++),it will make actnn more useful.Thank you~

**Comment by cjf00000** [comment]
Thanks for your interest in our work. ActNN is a library for reducing _training_ memory footprint by compressing the saved activations in each layer. At the inference time, the layer's activations won't be saved anyways, since we don't need to compute the gradients. Therefore, ActNN won't reduce the memory footprint at inference time.
